version: 2.1
jobs:

  test:
    working_directory: ~/ci
    docker:
      - image: district0x/cljs-dev:e701583
      - image: trufflesuite/ganache-cli:v6.7.0
        command: [-d, -m district0x, -p 8549, -l 80000000, --noVMErrorsOnRPCResponse, --b 1]
    steps:
      - checkout
      - restore_cache:
          name: Restore m2 package cache
          keys:
            - -v1-maven-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - -v1-maven-dependencies-
      - run: lein deps
      - save_cache:
          name: Save m2 package cache
          paths:
            - ~/.m2
          key: -v1-maven-dependencies-{{ checksum "project.clj" }}
      - restore_cache:
          name: Restore npm package cache
          keys:
            - -v1-npm-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install node modules
          command: lein npm install
      - save_cache:
          name: Save npm package cache
          key: -v1-npm-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: lein doo chrome-headless "tests" once

  deploy:
   machine: true
   steps:
     - checkout
     - run:
         name: Deploy to clojars
         command: lein release :patch

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          context: district0x
          requires:
            - test
          filters:
            branches:
              only: master
