version: 2.1

orbs:
   slack: circleci/slack@3.4.2

jobs:
  test:
    working_directory: ~/ci
    docker:
      - image: district0x/cljs-dev:02e2108
      - image: trufflesuite/ganache-cli:v6.9.1
        command: [-d, -m district0x, -p 8545, -l 80000000, --noVMErrorsOnRPCResponse]
    steps:
      - checkout
      - restore_cache:
          name: Restore npm package cache
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}
      - run:
          name: Install node modules
          command: npm install
      - save_cache:
          name: Save npm package cache
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules/
      - run:
          name: migrate contracts
          command: npx truffle migrate --network ganache
      - run:
          command:
            lein doo chrome-headless "browser-tests" once
      - slack/status:
          channel: travis-ci
          mentions: $CIRCLE_USERNAME

  deploy:
   machine: true
   steps:
     - checkout
     - run:
         name: Deploy to clojars
         command: lein release :patch
     - slack/status:
         channel: travis-ci
         mentions: $CIRCLE_USERNAME

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          context: district0x
      - approve_deploy:
          type: approval
      - slack/approval-notification:
          context: district0x
          message: Pending approval
      - deploy:
          context: district0x
          requires:
            - test
            - approve_deploy
          filters:
            branches:
              only: master
